### ISSUE TITLE
Design Of The App

### ISSUE THREAD

**Issue by umutphp** [AbduallahBarmu/QuotesApplication-#1]
Can you please change the app so that it looks like the screenshot below?

![design](https://user-images.githubusercontent.com/3245166/144506503-05c022a6-c0be-4535-9962-0ba1d1f4dc52.png)

**Comment by AbduallahBarmu** [comment]
Thanks for your feedback , I will try my best until I achieve the same
result on the  screenshot

best regards
Abduallah

**Comment by AbduallahBarmu** [comment]
What do you mean by *(tag-1) *?  is it * _id* of the quote because I could
not find any attribute with this name in the API  ?

**Comment by umutphp** [comment]
The shaed buttons are the list of tags of the quotes. A quote may have multiple tags. So "tag-1" was just a generic example for a tag name.

**Comment by AbduallahBarmu** [comment]
@umutphp 
I have finished the design as you required , also I  uploaded the apk version you can check **_APK_** file **_version2_** for the new design as it shown in **README** file

**Comment by umutphp** [comment]
Hi @AbduallahBarmu ,

Can you please send the APK file as you did before?

**Comment by AbduallahBarmu** [comment]
@umutphp 
for sure I have share it with you by mail
